name: demo
on:
  push:
    branches:
      - 'pipeline-dev'
env:
  COMMIT_ID: 5a47159a4e5a468cce7dc3ec83b9dc169a657c83

jobs:
  conditional_step:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v3
      with:
        repository: jabedhasan21/java-hello-world-with-gradle