name: demo
on:
  push:
    branches:
      - 'main'

jobs:
  conditional_step:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - shell: pwsh
      id: check_file_changed          
      run: |
        git diff --name-only HEAD~
        git diff --name-only HEAD~ > change.txt        
    - name: Upload list of changed files
      uses: actions/upload-artifact@v3
      with:
        name: changelist
        path: change.txt