name: demo
on:
  push:
    branches:
      - 'main'
env:
  COMMIT_ID: '992bac97d32bec88108d9ecca5abc97c5201944c'

jobs:
  conditional_step:
    runs-on: 'ubuntu-20.04'
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - shell: dash
      id: check_file_changed          
      run: |
        if [[ -n $COMMIT_ID ]]; 
              then
                git diff --name-only $COMMIT_ID
                git diff --name-only $COMMIT_ID > output/changes.txt
              else
                git diff --name-only HEAD~
                git diff --name-only HEAD~ > output/changes.txt
        fi        
    - name: Upload list of changed files
      uses: actions/upload-artifact@v3
      with:
        name: changelist
        path: change.txt